from django.db import models
from django.conf import settings
from django.utils import timezone

class ScrapeSource(models.Model):
    name = models.CharField(max_length=100, unique=True, help_text="e.g., Jordan News")
    base_url = models.URLField(max_length=255, unique=True)
    start_url = models.URLField(max_length=255, blank=True, null=True)
    language_code = models.CharField(max_length=5, default='en', help_text="ISO code (ar, en)")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class ResearchRequest(models.Model):
    class Status(models.TextChoices):
        PENDING = 'PENDING', 'Pending'
        RUNNING = 'RUNNING', 'Running'
        COMPLETED = 'COMPLETED', 'Completed'
        FAILED = 'FAILED', 'Failed'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    # Input Data
    topic = models.CharField(max_length=255, help_text="The research topic")
    target_url = models.URLField(max_length=1024, help_text="The specific URL to scrape")
    
    # --- NEW FIELD: User defined limit ---
    max_articles = models.PositiveIntegerField(
        default=10, 
        help_text="Maximum number of articles to scrape for this request."
    )
    
    # Pipeline State
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)
    created_at = models.DateTimeField(auto_now_add=True)
    
    # AI Output
    thematic_analysis = models.TextField(blank=True, null=True, help_text="Markdown text generated by Gemini")

    def __str__(self):
        return f"{self.topic} ({self.status})"

class Article(models.Model):
    request = models.ForeignKey(ResearchRequest, on_delete=models.CASCADE, related_name='articles', null=True, blank=True)
    source = models.ForeignKey(ScrapeSource, on_delete=models.SET_NULL, null=True, blank=True)
    url = models.URLField(max_length=1024, unique=True, db_index=True)
    title = models.CharField(max_length=500)
    clean_text = models.TextField()
    pub_date = models.DateTimeField(null=True, blank=True)
    author_name = models.CharField(max_length=150, blank=True, null=True)
    scraped_at = models.DateTimeField(default=timezone.now)
    downloaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='downloaded_articles')

    class Meta:
        ordering = ('-scraped_at',)
        verbose_name = "Archived Article"

    def __str__(self):
        return self.title[:50]