# Generated by Django 5.2.8 on 2025-11-08 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='core.scrapebatch')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('shein', 'Shein'), ('temu', 'Temu'), ('other', 'Other')], default='other', max_length=32)),
                ('category_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('fields', models.JSONField(default=list)),
                ('max_items', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='queued', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scrapebatch')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('shein', 'Shein'), ('temu', 'Temu'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('product_url', models.URLField(blank=True, db_index=True, max_length=2048)),
                ('image_url', models.URLField(blank=True, max_length=2048)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.scrapejob')),
            ],
        ),
        migrations.AddIndex(
            model_name='scrapejob',
            index=models.Index(fields=['status', 'created_at'], name='core_scrape_status_b9e8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['site', 'search_query', 'scraped_at'], name='core_produc_site_99c6da_idx'),
        ),
    ]
