# Generated by Django 5.2.8 on 2025-11-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='selectors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapejob_set', to='core.scrapebatch'),
        ),
    ]
