# Generated by Django 5.2.8 on 2025-11-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scrapejob_selectors_alter_scrapejob_batch'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_site_99c6da_idx',
        ),
        migrations.RemoveIndex(
            model_name='scrapejob',
            name='core_scrape_status_b9e8ac_idx',
        ),
        migrations.RemoveField(
            model_name='scrapebatch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scrapejob',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='scrapejob',
            name='selectors',
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='max_pages',
            field=models.PositiveIntegerField(default=0, help_text='Max pages to scrape. 0 for no limit.'),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='search_query',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.CharField(choices=[('shein', 'Shein'), ('temu', 'Temu'), ('dumyah', 'Dumyah'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapebatch',
            name='query',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scrapebatch'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='category_url',
            field=models.URLField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='max_items',
            field=models.PositiveIntegerField(default=0, help_text='Max items to scrape. 0 for no limit.'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='site',
            field=models.CharField(choices=[('shein', 'Shein'), ('temu', 'Temu'), ('dumyah', 'Dumyah'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PENDING', max_length=20),
        ),
    ]
