# Generated by Django 5.2.8 on 2025-11-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_core_produc_site_99c6da_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapejob',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.CharField(choices=[('shein', 'Shein'), ('temu', 'Temu'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scrapebatch',
            name='query',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapejob_set', to='core.scrapebatch'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='max_items',
            field=models.PositiveIntegerField(default=50, help_text='Max items to scrape. 0 for no limit.'),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='site',
            field=models.CharField(choices=[('shein', 'Shein'), ('temu', 'Temu'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
