# Generated by Django 5.2.8 on 2025-11-10 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_scrapejob_updated_at_alter_product_site_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapebatch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='fields',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='selectors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.CharField(choices=[('shein', 'Shein'), ('temu', 'Temu'), ('dumyah', 'DUMYAH'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='site',
            field=models.CharField(choices=[('shein', 'Shein'), ('temu', 'Temu'), ('dumyah', 'DUMYAH'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
