# Generated by Django 5.2.8 on 2025-12-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_rating_product_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='pagination_type',
            field=models.CharField(choices=[('single', 'Single Page Only'), ('next', 'Next Button'), ('infinite', 'Infinite Scroll')], default='single', help_text='How does the website load more products?', max_length=20),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='used_api',
            field=models.BooleanField(default=False, help_text='Whether internal API was used'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.CharField(choices=[('dumyah', 'DUMYAH'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='site',
            field=models.CharField(choices=[('dumyah', 'DUMYAH'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
