# Generated by Django 5.0 on 2026-01-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapebatch',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
