# Generated by Django 5.0 on 2026-01-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scrapebatch_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapebatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
