# Generated by Django 5.0 on 2026-01-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scrapebatch_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapebatch',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='scrapebatch',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
