# Generated by Django 5.0 on 2026-02-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_scrapebatch_updated_at_scrapebatch_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='max_items',
            field=models.PositiveIntegerField(default=0, help_text='Max items to scrape. 0 for no limit.'),
        ),
    ]
