# Generated by Django 5.0 on 2025-11-24 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Jordan News', max_length=100, unique=True)),
                ('base_url', models.URLField(max_length=255, unique=True)),
                ('start_url', models.URLField(blank=True, help_text='e.g. , https://www.jordannews.com/archive.xml', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language_code', models.CharField(default='ar', help_text='ISO 639-1 code (ar, en)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(db_index=True, help_text='The verifiable link to the original article.', max_length=511, unique=True)),
                ('pub_date', models.DateTimeField(db_index=True, help_text='The date/time the article was published.')),
                ('title', models.CharField(max_length=500)),
                ('clean_text', models.TextField(help_text='The fully cleaned, structured text content.')),
                ('ai_train_allowed', models.BooleanField(db_index=True, default=True, help_text='Set to False if source signals ai-train=no or explicitly excludes training.')),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_scraped', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_etl.scrapesource')),
            ],
            options={
                'verbose_name': 'Archived Article',
                'verbose_name_plural': 'Archived Articles',
                'ordering': ('-pub_date',),
                'indexes': [models.Index(fields=['source', 'pub_date'], name='archive_etl_source__7f24f2_idx'), models.Index(fields=['source', 'ai_train_allowed'], name='archive_etl_source__0674ef_idx')],
            },
        ),
    ]
