# Generated by Django 5.0 on 2025-11-24 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_etl', '0002_researchrequest_article_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-scraped_at',), 'verbose_name': 'Archived Article'},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='archive_etl_source__7f24f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='archive_etl_source__0674ef_idx',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_scraped',
            new_name='scraped_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source_url',
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, default='http://placeholder.url', max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='ai_train_allowed',
            field=models.BooleanField(default=True, help_text='False if robots.txt forbids AI training.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='clean_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='downloaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_etl.scrapesource'),
        ),
    ]
