# Generated by Django 5.0 on 2025-11-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_etl', '0003_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrequest',
            name='max_articles',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of articles to scrape for this request.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ai_train_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='researchrequest',
            name='topic',
            field=models.CharField(help_text='The research topic', max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapesource',
            name='language_code',
            field=models.CharField(default='en', help_text='ISO code (ar, en)', max_length=5),
        ),
        migrations.AlterField(
            model_name='scrapesource',
            name='start_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
