# Generated by Django 5.0 on 2025-11-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_etl', '0004_researchrequest_max_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ai_train_allowed',
        ),
    ]
