# Generated by Django 5.0 on 2026-01-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='file_search_store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
