# Generated by Django 5.0 on 2026-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='context_type',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='file_search_store_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='related_batch_id',
        ),
        migrations.AddField(
            model_name='chatdocument',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
